### ISSUE TITLE
Can't open files with space.

### ISSUE THREAD

**Issue by rmariuzzo** [cube-root/directory-serve#12]
When I click on a file that contains a space (`013 - Image 1.png`) a new tab is opened as: `http://10.0.0.9:1234/013 -`.

![image](https://user-images.githubusercontent.com/439839/199731071-0b2f4326-14d6-4795-ab8c-19ae6ddd11ab.png)

![image](https://user-images.githubusercontent.com/439839/199731139-4ca326e1-c4fc-424a-a347-00ba91aa2f97.png)

**Comment by rmariuzzo** [comment]
I think the `file` should be escaped here: https://github.com/cube-root/directory-serve/blob/aa0b529c05fc0a74403dc1e260433cddd6a5228a/lib/middleware/directory.js#L39

**Comment by abhisawesome** [comment]
Fixed the download issue. @rmariuzzo 

https://github.com/cube-root/directory-serve/pull/13

**Comment by rmariuzzo** [comment]
Thank you, good job.
