### ISSUE TITLE
Serve tailwind.css locally

### ISSUE THREAD

**Issue by tornikeshavishvili** [cube-root/directory-serve#20]
There are use cases when we will need to use this utility in private networks for example, which may not have internet access.

For such cases we recommend to serve tailwind css locally not from cdn.

Best Regards
Tornike

**Comment by abhisawesome** [comment]
@hasimpk

**Comment by abhisawesome** [comment]
Fixed the issue

**Comment by abhisawesome** [comment]
https://github.com/cube-root/directory-serve/pull/38

https://github.com/cube-root/directory-serve/pull/36
